baseurl = "https://jploskonka.github.io"
languageCode = "en"
title = "jploskonka"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/jploskonka\">jploskonka</a> 2017"
disqusShortname = "codenroll-it"
googleAnalytics = "UA-89853504-1"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true 

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "code'n'roll.it" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "codenrollit"
github = "jploskonka"
email = "ploskonkajakub@gmail.com"
linkedin = ""
facebook = ""
instagram = ""
codepen = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
