version: 2

general:
  branches:
    only:
      - source

jobs:
  build:
    docker:
      - image: jojomi/hugo:0.30.2

    steps:
      - run: apk update && apk upgrade && apk add bash git # TODO: Move this to container
      - checkout
      - run: ./publish_to_ghpages.sh
