version: 2

general:
  branches:
    only:
      - source

jobs:
  build:
    docker:
      - image: jojomi/hugo:0.30.2

    steps:
      - run: 
          command: |
            apk update && \
            apk upgrade && \
            apk add bash git openssh # TODO: Move this to container

      - add_ssh_keys: 
          fingerprint: 74:c6:05:48:a8:d5:cb:32:e3:9a:fc:e7:67:4a:63:7f
      - run: git config --global user.email bot@example.com
      - run: git config --global user.name CircleCI

      - checkout
      - run: ./publish_to_ghpages.sh
